### ISSUE TITLE
Create a unit test for encrypt and decrypt functions

### ISSUE THREAD

**Issue by ourarash** [EdoToji/CECS-491A-Project#2]

**Comment by BrandonDelliquadri** [comment]
Using the "npm run test" now uses mocha to check that our file encryption and decryption works. This works by encrypting a 1kb file and checking if the encrypted file matches the same file encrypted in a verified working version of Musashi. Same for testing decryption, it decrypts the encrypted file and checks it with the same file decrypted in a verified working version of Musashi
